# Generated by Django 5.0.1 on 2024-01-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_category_product_productshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_per_km', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
