# Generated by Django 5.0.1 on 2024-01-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='sheet_ID',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
