# Generated by Django 5.0.1 on 2024-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
