# Generated by Django 5.0.1 on 2024-01-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_sheet_id_business_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
