# Generated by Django 5.0.1 on 2024-02-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_business_bin_alter_business_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bin',
            new_name='bin_no',
        ),
    ]
