# Generated by Django 5.0.2 on 2024-02-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_rating_business_business_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_mins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('has_delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_shop', to='core.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productshop')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_shop', to='core.business')),
            ],
        ),
    ]
