# Generated by Django 5.0.2 on 2024-02-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='duration_mins',
        ),
    ]
