# Generated by Django 5.0.2 on 2024-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_hubconfiguration_delete_fareconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
